openapi: 3.1.0
info:
  description: >
    ## UMBRELLA API Documentation Description:

    Welcome to the official documentation for the UMBRELLA RESTful API. 

    This comprehensive guide is designed to assist developers and integrators, 

    in effectively utilizing the power of our API.

    Our RESTful API provides:

    A simple and efficient way to access and interact 

    with, currencies, finances ....... 

    Whether you're building 

    a web application, mobile app, or integrating 

    with other services, our API offers the tools 

    you need to streamline your development process 

    and unlock the full potential of your project.

    In this documentation, you'll find detailed 

    information on how to make API requests, 

    authentication procedures, available endpoints, 

    request/response examples, error handling, 

    and best practices for integrating UMBRELLA

    into your projects.


    ## Authorization:

    You can authorize your requests using this authorization method:

    - TOKEN


    ## TOKEN

    - The endpoints are authorized using a TOKEN.

    - To authorize requests, please add a Token using the 'Authorize' button
    with the following format:
      ### "Bearer user-token"
  version: 1.0.0
  contact:
    name: API Support
    email: shadab@gmail.com
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: currency
    description: currency - currency data handling.
  - name: scheduled rate update
    description: scheduled rate update - scheduled rate update data handling.
  - name: fiscal year
    description: fiscal year - fiscal year data handling.

paths:
  /umbrella/currencies:
    get:
      tags:
        - currency
      summary: Get currency details.
      description: Get currency details.
      operationId: getCurrencies
      responses:
        '200':
          description: List of currencies.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    data:
                      type: array
                      properties:
                        type: object
                        active:
                          type: boolean
                        code:
                          type: string
                        id:
                          type: integer
                        name:
                          type: string
                        numeric_code:
                          type: string
                        rate:
                          type: float
                        symbol:
                          type: string
                    errors:
                      type: object
                    pagination:
                      type: object
                      page:
                        type: integer
                      per_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_records:
                        type: integer
                    status:
                      type: integer
                    success_message:
                      type: string
              required:
                - code
              example:
                data:
                  - active: true
                    code: AFN
                    id: 1
                    name: Afghani
                    numeric_code: ''
                    rate: 0
                    symbol: AFN
                errors: null
                pagination:
                  page: 1
                  per_page: 100
                  total_pages: 1
                  total_records: 1
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
  '/umbrella/currencies/{obj_id}':
    get:
      tags:
        - currency
      summary: Get one currency.
      description: Get one currency.
      operationId: getCurrencyById
      parameters:
        - name: obj_id
          in: path
          schema:
            type: integer
          rquired: true
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    data:
                      type: array
                      properties:
                        type: object
                        active:
                          type: boolean
                        code:
                          type: string
                        digits:
                          type: integer
                        id:
                          type: integer
                        name:
                          type: string
                        numeric_code:
                          type: string
                        rate:
                          type: float
                        rates:
                          type: array
                        rounding:
                          type: float
                        symbol:
                          type: string
                    errors:
                      type: null
                    pagination:
                      type: null
                    status:
                      type: integer
                    success_message:
                      type: null
              example:
                data:
                  active: true
                  code: AFN
                  digits: 2
                  id: 1
                  name: Afghani
                  numeric_code: ''
                  rate: 0
                  rates: []
                  rounding: 0.01
                  symbol: AFN
                errors: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
        '404':
          description: 404 Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP404'
    post:
      tags:
        - currency
      summary: Create a currency.
      description: Create a currency.
      operationId: postCurrencyById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/CreateCurrency'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    data:
                      type: array
                      properties:
                        type: object
                        active:
                          type: boolean
                        code:
                          type: string
                        digits:
                          type: integer
                        id:
                          type: integer
                        name:
                          type: string
                        numeric_code:
                          type: string
                        rate:
                          type: float
                        rates:
                          type: array
                        rounding:
                          type: float
                        symbol:
                          type: string
                    errors:
                      type: null
                    pagination:
                      type: null
                    status:
                      type: integer
                    success_message:
                      type: null
              example:
                data:
                  active: true
                  code: AFN
                  digits: 2
                  name: Afghani
                  numeric_code: '001'
                  rate: 0
                  rates: []
                  rounding: 3
                  symbol: AFN
                errors: null
                pagination: null
                status: 201
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
    put:
      tags:
        - currency
      summary: Update a currency.
      description: Update a currency.
      operationId: updateCurrencyById
      parameters:
        - name: obj_id
          rquired: true
          in: path
          schema:
            type: integer
          example: 19
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/UpdateCurrency'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type: object
                        active:
                          type: boolean
                        code:
                          type: string
                        digits:
                          type: integer
                        id:
                          type: integer
                        name:
                          type: string
                        numeric_code:
                          type: string
                        rate:
                          type: float
                        rates:
                          type: array
                        rounding:
                          type: float
                        symbol:
                          type: string
                    errors:
                      type: null
                    pagination:
                      type: null
                    status:
                      type: integer
                    success_message:
                      type: null
              example:
                data:
                  active: true
                  code: eu1
                  digits: 3
                  name: Euro
                  numeric_code: '111'
                  rate: 0
                  rates: []
                  rounding: 1
                  symbol: eu
                errors: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
    delete:
      tags:
        - currency
      summary: Delete a currency.
      description: Delete a currency.
      operationId: deleteCurrencyById
      parameters:
        - name: obj_id
          rquired: true
          in: path
          schema:
            type: integer
          example: 19
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    data:
                      type: null
                    errors:
                      type: null
                    pagination:
                      type: null
                    status:
                      type: integer
                    success_message:
                      type: null
              example:
                data: null
                errors: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
  '/umbrella/fiscal-years':
    get:
      tags:
        - fiscal year
      summary: Get list of fiscal years.
      description: Get list of fiscal years.
      operationId: getFiscalYears
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    data: null
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        state:
                          type: string
                    errors:
                      type: object
                    pagination:
                      items:
                        type: object
                      properties:
                        page:
                          type: integer
                        per_page:
                          type: integer
                        total_pages:
                          type: integer
                        total_records:
                          type: integer
                    status:
                      type: integer
                    success_message:
                      type: string
              example:
                data:
                  - id: 2
                    name: "2024"
                    state: "open"
                errors: null
                pagination:
                  page: 1
                  per_page: 100
                  total_pages: 1
                  total_records: 1
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
  
  '/umbrella/fiscal-years/{obj_id}':
    get:
      tags:
        - fiscal year
      summary: Get one fiscal year.
      description: Get one fiscal year.
      operationId: getFiscalYearById
      parameters:
        - name: obj_id
          in: path
          schema:
            type: integer
          rquired: true
          example: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    company:
                      type: integer
                    company_:
                      type: object
                      label:
                        type: string
                      value:
                        type: integer
                    end_date:
                      type: date
                    id:
                      type: integer
                    name:
                      type: string
                    periods:
                      type: array
                      properties:
                        items:
                        type: object
                        company:
                          type: integer
                        company_:
                          type: object
                          label:
                            type: string
                          value:
                            type: integer
                        end_date:
                          type: date
                        id:
                          type: integer
                        name:
                          type: string
                        post_move_sequence:
                          type: integer
                        post_move_sequence_:
                          type: object
                          label:
                            type: string
                          value:
                            type: integer
                        start_date:
                          type: date
                        state:
                          type: string
                    post_move_sequence:
                      type: integer
                    post_move_sequence_:
                      type: object
                      label:
                        type: string
                      value:
                        type: integer
                    start_date:
                      type: date
                    state:
                      type: string
                errors:
                  type: object
                pagination:
                  items:
                    type: object
                  properties:
                    page:
                      type: integer
                    per_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_records:
                      type: integer
                status:
                  type: integer
                success_message:
                  type: string
              example:
                data:
                  company: 1
                  company_:
                    label: Party 1
                    value: 1
                  end_date: "2024-12-31"
                  id: 2
                  name: "2024"
                  periods:
                    - company: 1
                      company_:
                        label: Party 1
                        value: 1
                      end_date: "2024-01-31"
                      fiscalyear: 2
                      id: 13
                      name: "2024-01"
                      post_move_sequence: 4
                      post_move_sequence_:
                        label: "2024"
                        value: 4
                      start_date: "2024-01-01"
                      state: open
                      type: standard
                  post_move_sequence: 4
                  post_move_sequence_:
                    label: "2024"
                    value: 4
                  start_date: "2024-01-01"
                  state: open
                errors: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP401'
        '404':
          description: 404 Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTP404'
    delete:
        tags:
          - fiscal year
        summary: Delete a fiscal year.
        description: Delete a fiscal year.
        operationId: deleteFiscalYearById
        parameters:
          - name: obj_id
            rquired: true
            in: path
            schema:
              type: integer
            example: 2
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  items:
                    type: object
                    properties:
                      data:
                        type: null
                      errors:
                        type: null
                      pagination:
                        type: null
                      status:
                        type: integer
                      success_message:
                        type: null
                example:
                  data: null
                  errors: null
                  pagination: null
                  status: 200
                  success_message: null
          '401':
            description: >-
              401 Unauthorized: The server could not verify that you are
              authorized to access the URL requested. You either supplied the
              wrong credentials (e.g. a bad password), or your browser doesn't
              understand how to supply the credentials required.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/HTTP401'
components:
  schemas:
    CreateCurrency:
      properties:
        active:
          type: boolean
        code:
          type: string
        digits:
          type: integer
        name:
          type: string
        numeric_code:
          type: string
        rounding:
          type: float
        symbol:
          type: string
      required:
        - code
        - name
      example:
        active: true
        code: nc2
        digits: 2
        name: new_currency
        numeric_code: '001'
        rounding: 4
        symbol: nc2
    UpdateCurrency:
      properties:
        active:
          type: boolean
        code:
          type: string
        digits:
          type: integer
        name:
          type: string
        numeric_code:
          type: string
        rounding:
          type: float
        symbol:
          type: string
      required:
        - code
        - id
      example:
        active: true
        code: er1
        digits: 3
        name: Euro
        numeric_code: '111'
        rounding: 2
        symbol: eu
    CreateCron:
      properties:
        data:
          type: object
          properties:
            type: object
            currencies:
              type: array
            currency:
              type: integer
            currency_:
              type: object
              label:
                type: string
              value:
                type: integer
            day:
              type: integer
            frequency:
              type: string
            last_update:
              type: date
            source:
              type: string
            weekday:
              type: integer
      required:
        - currency
        - frequency
        - source
      example:
        data:
          currency: 1
          day: 1
          frequency: monthly
          last_update: '2024-01-28'
          source: ecb
          weekday: 'ir.calendar.day,2'
    UpdateCron:
      properties:
        data:
          type: object
          properties:
            type: object
            currencies:
              type: array
            currency:
              type: integer
            currency_:
              type: object
              label:
                type: string
              value:
                type: integer
            day:
              type: integer
            frequency:
              type: string
            last_update:
              type: date
            source:
              type: string
            weekday:
              type: integer
      required:
        - currency
        - frequency
        - source
      example:
        data:
          currency: 1
          day: 1
          frequency: monthly
          last_update: '2024-01-28'
          source: ecb
          weekday: 'ir.calendar.day,2'
    CreateFiscalYear:
      properties:
        data:
          type: object
          properties:
            type: object
            currencies:
              type: array
            currency:
              type: integer
            currency_:
              type: object
              label:
                type: string
              value:
                type: integer
            day:
              type: integer
            frequency:
              type: string
            last_update:
              type: date
            source:
              type: string
            weekday:
              type: integer
      required:
        - currency
        - frequency
        - source
      example:
        data:
          currency: 1
          day: 1
          frequency: monthly
          last_update: '2024-01-28'
          source: ecb
          weekday: 'ir.calendar.day,2'
    HTTP200:
      properties:
        success_message:
          type: string
          example: OK
    HTTP401:
      properties:
        data:
          type: null
        errors:
          type: object
        pagination:
          type: null
        status:
          type: integer
        success_message:
          type: string
      example:
        data: null
        errors:
          - error_message: >-
              401 Unauthorized: The server could not verify that you are
              authorized to access the URL requested. You either supplied the
              wrong credentials (e.g. a bad password), or your browser doesn't
              understand how to supply the credentials required.
            identifier: Global
            severity: 1
        pagination: null
        status: 401
        success_message: null
    HTTP404:
      properties:
        data:
          type: null
        errors:
          type: array
          properties:
            error_message:
              type: string
            identifier:
              type: string
            serverity:
              type: integer
        pagination:
          type: null
        status:
          type: integer
        success_message:
          type: string
      example:
        data: null
        errors:
          - error_message: Not found
            identifier: currency.currency
            severity: 1
        pagination: null
        status: 404
        success_message: null
    HTTP400:
      properties:
        data:
          type: null
        errors:
          type: array
          properties:
            error_message:
              type: string
            identifier:
              type: string
            serverity:
              type: integer
        pagination:
          type: null
        status:
          type: integer
        success_message:
          type: string
      example:
        data: null
        errors:
          - error_message: >-
              415 Unsupported Media Type: Did not attempt to load JSON data
              because the request Content-Type was not 'application/json'.
            identifier: Global
            severity: 1
        pagination: null
        status: 400
        success_message: null
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
